name = "your-worker-name"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 应用入口点配置 - 使用 Cloudflare Workers 入口文件
main = "./cloudflare-worker.js"

# Next.js 应用程序配置
[build]
command = "npm run build"
cwd = "."
watch_dir = "app"

[dev]
port = 3000

# 静态资源配置
[site]
bucket = "./.next/static"
include = ["public/*"]

# KV 存储绑定
[[kv_namespaces]]
binding = "KV"
preview_id = "your-kv-preview-id"
id = "your-kv-production-id"

# R2 存储绑定
[[r2_buckets]]
binding = "R2"
bucket_name = "your-r2-bucket-name"
preview_bucket_name = "your-r2-preview-bucket-name"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "your-d1-database-name"
database_id = "your-d1-database-id"
migrations_dir = "prisma/migrations-d1"

[vars]
ENVIRONMENT = "production"
NODE_ENV = "production"

# Cloudflare AI Gateway 配置
[ai]
binding = "AI"

# 开发环境配置
[env.development]
# 覆盖生产环境的变量
[env.development.vars]
ENVIRONMENT = "development"
NODE_ENV = "development"

[[env.development.kv_namespaces]]
binding = "KV"
id = "your-kv-development-id"

[[env.development.r2_buckets]]
binding = "R2"
bucket_name = "your-r2-development-bucket"

[[env.development.d1_databases]]
binding = "DB"
database_name = "your-d1-development-database"
database_id = "your-d1-development-database-id"

# 预发布环境配置
[env.staging]
# 覆盖生产环境的变量
[env.staging.vars]
ENVIRONMENT = "staging"
NODE_ENV = "production"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "your-kv-staging-id"

[[env.staging.r2_buckets]]
binding = "R2"
bucket_name = "your-r2-staging-bucket"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "your-d1-staging-database"
database_id = "your-d1-staging-database-id" 