# Cloudflare Pages 配置文件
# 专门用于 Pages + Functions 部署

# 应用基本信息
name = "remove-anything"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages 特定配置
pages_build_output_dir = ".vercel/output"

# 环境变量
[vars]
ENVIRONMENT = "production"
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://remove-anything.pages.dev"

# KV 存储绑定
[[kv_namespaces]]
binding = "KV"
preview_id = "your-kv-preview-id"
id = "your-kv-production-id"

# R2 存储绑定
[[r2_buckets]]
binding = "R2"
bucket_name = "remove-anything-storage"
preview_bucket_name = "remove-anything-storage-preview"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "remove-anything-db"
database_id = "your-d1-database-id"

# AI Gateway 绑定
[ai]
binding = "AI"

# 开发环境配置
[env.development]
[env.development.vars]
ENVIRONMENT = "development"
NODE_ENV = "development"
NEXT_PUBLIC_SITE_URL = "http://localhost:3000"

[[env.development.kv_namespaces]]
binding = "KV"
id = "your-kv-development-id"

[[env.development.r2_buckets]]
binding = "R2"
bucket_name = "remove-anything-storage-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "remove-anything-db-dev"
database_id = "your-d1-development-database-id"

# Pages Functions 配置
[functions]
# 兼容性设置
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 函数路由配置
[[functions.routes]]
pattern = "/api/*"
method = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]

[[functions.routes]]
pattern = "/_next/image/*"
method = ["GET"] 